TARGET = circle celsius2Fahr fahr2Celsius fahr2Celsius2 fahr2Celsius3 limits literal score triangle

all: ${TARGET}

# You must don't have object file before compile
# circle: circle.c
# $@ : current directory
circle: $@
celsius2Fahr: $@
fahr2Celsius: $@
fahr2Celsius2: $@
fahr2Celsius3: $@
limits: $@
literal: $@
score: $@
triangle: $@

clean:
	rm -f ${TARGET}
